### ISSUE TITLE
Ensure cache for Relaton works?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#43]
Recently it seems that Metanorma runs always require a full download of references?

```
Local cache version is obsolete.
```

Do we have tests to ensure that the caching works?

e.g.

```adoc
* [[[ISO19107,ISO 19107]]], _AUTOFILL_
```

ping @andrew2net

**Comment by andrew2net** [comment]
@ronaldtse is it urgent?

**Comment by ronaldtse** [comment]
Probably other priorities first?

**Comment by opoudjis** [comment]
That error message happens whenever you update the version of relaton: it assumes that the XML in the cache is no longer valid. It isn't a bug at all; at most, get @andrew2net to update the error message.

**Comment by ronaldtse** [comment]
But I’ve been using the same version of relaton (did not do bundle update).

**Comment by opoudjis** [comment]
Welp, that's how the error message is generated. The version of relaton is coded into the cache (at your request), and is checked every time the local cache is accessed. The global cache, OTOH, is simply overwritten if the relaton version changes.

**Comment by ronaldtse** [comment]
My point was two back to back runs of metanorma should not need relaton to refetch documents (set to local mode), which it seems to do once in a while. Maybe there’s something funny in the cache version file (which seems to still be a pstore file?).

**Comment by andrew2net** [comment]
@ronaldtse if the bib model is changed then items could not be read from old XML files. But I agree, we don't have to update a cache every time the `relaton` gem version changed.
I suggest it should update the cache if the version of `relaton-bib` or `relaton-iso-bib` is changed.
@opoudjis maybe we should add element `version` to XML? So the document will be refetched only if its flavor gem version is changed. We don't have to delete entire cash in this case.

**Comment by opoudjis** [comment]
@ronaldtse Given how radically relaton modelling is changing lately, I disagree. If the XML is going to look different, the cache must be flushed. Non-negotiable. If you want the XML to be stable, then don't ask for it to be refactored.

The only thing that can be done here is for us to manually keep track of when an update to the relaton suite will impact the XML output, through the proposed bib-version. I think that is a terrible idea, since it is guaranteed that someone somewhere will forget to update the bib-version variable; and note that this is not just relaton-bib and relaton-iso-bib, but also the remaining relaton gems, where they involve bibdata/ext.

No. It is safer to reload the cache, and if you don't want periodic reloads, then don't keep asking the relaton stack to change.

**Comment by ronaldtse** [comment]
@opoudjis if the XML schema has changed, we must refetch cache.

This ticket assumes no schema change.

**Comment by opoudjis** [comment]
But how do you know there is no schema change, unless we manually indicate it in the gem? And that introduces potential for error.

**Comment by ronaldtse** [comment]
It sounds like we should start versioning the schema. Not necessarily for this specific reason, but it's kind of inevitable.

**Comment by andrew2net** [comment]
The schema could be changed in the `relaton-bib`, `relaton-iso-bib`, or flavor gems. We can update a document if the gem generated it is changed.
For example `relaton-iso` has version "0.5.0". If we store the version number into new `bib-version` element:
```
<bibitem>
  <bib-version>0.5.0</bib-version>
  ...
</bibitem>
```
then we can update the document if version of `relaton-iso` changed to "0.5.1". We don't have to purge all the documents. We can chech version of document in fetch function.

**Comment by opoudjis** [comment]
> The schema could be changed in the relaton-bib, relaton-iso-bib, or flavor gems. We can update a document if the gem generated it is changed.

Which is going to be no different to the behaviour @ronaldtse finds annoying, and in fact he's going to find it even more annoying, because those gems change more frequently (though the resulting behaviour is in fact more accurate). Ronald is explicitly requesting the schema be versioned separately, i.e. manually.

Ronald, I've said why this is a bad idea for maintenance, in a stack that is already clearly unmaintainable. Relaton is not my stack any more though, so this will not be my problem, it will be Andrej's.

**Comment by andrew2net** [comment]
@ronaldtse could we close this issue?

**Comment by opoudjis** [comment]
No.

Let me suggest this: Relaton includes a hash of the biblio.rng file in its cache, replacing the version number, which is clearly not fit for purpose. Every time relaton accesses the cache, it compares the hash of its biblio.rng file with the hash stored in the cache.

That's not quite it either, because there can be schema changes in bibdata/ext, and there can be changes in the internal data types. But it is better than what is going on now.

**Comment by andrew2net** [comment]
@opoudjis do you mean we should put the `biblio.rng` form the metanorma-model-iso to the relaton for control the model changes?
I think in this case we should add a test to check grammar of XML files against `biblio.rng`.  It needs to be sure the BibliographicItem class updated as well.
How about flavor gems? Do we need to include their `*.rng` files and control model changes?

**Comment by andrew2net** [comment]
this issue duplicates that https://github.com/metanorma/relaton/issues/54
